# Generated by Django 5.2.3 on 2026-02-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
